name = "Mutt Compose"
grammar = "mutt_compose"
path_suffixes = ["mutt-compose"]
line_comments = ["# "]
bracket_pairs = [
  { start = "[", end = "]" },
  { start = "{", end = "}" },
  { start = "(", end = ")" },
  { start = "<", end = ">" },
  { start = '"', end = '"' },
  { start = "'", end = "'" },
]